# Generated by Django 3.1.4 on 2021-02-11 01:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Picture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='upload_pict/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'gif'])], verbose_name='アップロード画像')),
                ('uploader', models.CharField(max_length=200)),
                ('uploadDate', models.DateField()),
                ('updateDate', models.DateField()),
                ('deleteFlg', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='T_UserToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('AuthenticateToken', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('applyDateEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='M_User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=400, unique=True)),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('updateDate', models.DateField()),
                ('deleteFlg', models.BooleanField()),
                ('bannedFlg', models.BooleanField()),
                ('UserTokenId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='T_UserToken', to='memFrame.t_usertoken')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
