# Generated by Django 3.1.4 on 2021-04-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memFrame', '0002_t_picture_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_picture',
            old_name='userId',
            new_name='M_UserId',
        ),
    ]
